### ISSUE TITLE
Posts Not Viewable

### ISSUE THREAD

**Issue by 0x44RU5H** [HereIsKevin/hereiskevin.github.io#1]
On the website [hereiskevin.github.io](https://hereiskevin.github.io), text on blog posts are not viewable due to the default color of text tags set in the CSS configuration. Changing the text color to white would allow viewers to read the blog post.

**Comment by HereIsKevin** [comment]
Hmm. I can't seem to reproduce this issue on my end. Could you upload a screenshot?

**Comment by HereIsKevin** [comment]
Fixed and resolved with 09a9c41892dbe9de6774e0363f3c127481a2cb8b.
